---
- name: Checking latest versions of httpd and mariadb
  hosts: web
  become: true
  tasks:
    - name: Ensure httpd and mariadb are at the latest version
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: latest
      loop:
        - httpd
        - mariadb

    - name: Ensure httpd and mariadb services are started
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
      loop:
        - httpd
        - mariadb
 