---
- name: Checking latest versions of httpd
  hosts: all
  become: true
  tasks:
    - name: Ensure {{ service }} latest version
      ansible.builtin.dnf:
        name: "{{ service }}"
        state: latest

    - name: Ensure {{ service }} started
      ansible.builtin.systemd:
        name: "{{ service }}"
        state: started