---
- name: checking latest versions of httpd and mariadb
  hosts: web
  become: true
  tasks: 
   - name: ensure httpd is at the latest version 
     ansible.builtin.dnf: 
      name="{{ item }}"
      state=latest
    loop:
    - httpd
    - mariadb

   - name: ensure httpd server is started
     ansible.builtin.service:
      name="{{ item }}" 
      state=started
    loop:
    - httpd
    - mariadb