---
- name: checking latest version
  hosts: all
  become: true
  tasks: 
   - name: ensure httpd is at the latest version 
     dnf: 
      name=httpd 
      state=latest

   - name: ensure httpd server is started
     systemd: 
      name=httpd 
      state=started

   - name: ensure mariadb is at the latest version
     dnf: 
      name=mariadb-server 
      state=latest

   - name: ensure maiadb is started
     systemd: 
      name=mariadb 
      state=started
