---
- name: make sure apache is installed and started
  hosts: web
  become: true
  tasks:
  - name: make sure apache is installed
    ansible.builtin.dnf:
      name: "{{ service }}"
      state: "installed"

  - name: make sure apache is started
    ansible.builtin.systemd:
      name: "{{ service }}"
      state: "started"