---
- name: save the command output
  hosts: web
  tasks:
  - name: save the output
    ansible.builtin.shell: ls /home
    register: homes

  - name: display the output
    ansible.builtin.debug:
     var: homes.stdout_lines[0]