---
- name: save the command output
  hosts: web
  tasks:
  - name: save the output
    ansible.builtin.shell: ls /home
    register: output_home

  - name: display the output
    ansible.builtin.debug:
     var: ls /home output is output_home.stdout_lines