---
- name: save the command output
  hosts: 
  tasks:
  - name: save the output
    ansible.builtin.shell: ls /home/ec2-user/Ansible/
    register: homes

  - name: display the output
    ansible.builtin.debug:
     var: homes.stdout_lines