---
- name: save the command output
  hosts: web
  tasks:
  - name: save the output
    ansible.builtin.command: ls /home
    register: output_home

  - name: display the output
    ansible.builtin.debug:
     msg: ls /home output is {{ output_home }}