---
- name: create 4 Users 
  hosts: all
  become: true
  tasks: 
  - name: creating users using loop:
    ansible.builtin.user:
      name: "{{ item }}"
      state: present
      groups: "users"
    loop:
     - latha
     - bhaskar
     - nirshan
     - ranhitha