---
- name: create 4 Users 
  hosts: all
  become: true
  tasks: 
  - name: Ensure 'users' group exists
    ansible.builtin.group:
     name: users
     state: present

  - name: Create users using a loop
    ansible.builtin.user:
      name: "{{ item }}"
      state: present
      groups: "users"
    loop:
      - latha
      - bhaskar
      - nirshan
      - ranhitha









