---
- name: print the Variables from prompt
  hosts: all
  connection: local
  vars_prompt:
  - name: COURSE
    prompt: please enter the name of the course
  - name: DURATION
    prompt: please enter the duration

  tasks:
  - name: printing values from prompt
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}"