---
- name: Devops course information
  hosts: all
  vars:
   course-name: "devops with aws"
   duration: 120 120HRS
   trainer: Sivakumar
   topics:
   - linux
   - scripting
   - ansible
   - aws
   live: true
   tool:
     ci: jenkins
     cloud: aws
     containarazation: docker
  tasks:
  - name: Print course information
    ansible.builtin.debug:
     msg: "Hello I am learning {{ course-name }}, duration is {{ duration }}, trainer is {{ trainer }}, topics are {{ topics }}, is it {{ live }}, tools covered are {{ tool }}"