---
- name: installing multiple packages using loop
  hosts: all
  become: yes
  tasks:
  - name: installing package
    ansible.builtin.service:
      name: "{{ item }}"
      state: installed
    loop:
    - mysql
    - tree
    - zip
    - httpd