---
- name: filters
  hosts: all  
  tasks:
  - name: convert string to list
    vars:
      fruits: "apple, banana, orange"
    ansible.builtin.debug:
      msg: "Fruits are {{ fruits | split(',') }}"
      
  - name: convert map into list
    vars:
      course: 
        name: linux
        duration: 10 days
        trainer: siva
    ansible.builtin.debug:
      msg: "Course info: {{ course | dict2items }}"

  - name: convert lower case 
    vars:
      name: "G. Latha BHAskar" 
    ansible.builtin.debug:
     msg: "Hello {{ name | lower }}"

 - name: convert Upper case 
   vars:
     name: "G. Latha BHAskar" 
   ansible.builtin.debug:
    msg: "Hello {{ name | upper }}"