---
- name: filters
  hosts: all  
  tasks:
  - name: convert string to list
    vars:
      fruits: "apple, banana, orange"
    ansible.builtin.debug:
      msg: "Fruits are {{ fruits | split(',') }}"
      