---
- name: configure backend server
  hosts: backend
  become: yes
  tasks:
  - name: disable current nodejs module
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs 20 module
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present
      
  - name: create expence user
    ansible.builtin.user:
      name: expence

  - name: create directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download the code into created directory
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip

  - name: unzip the code
    ansible.builtin.unarchive:
      src: /tmp/backend.zip
      dest: /app