---
- name: configure frontend server
  hosts: frontend
  become: yes
  tasks: 
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: installed

  - name: enable and start the nginx service
    ansible.builtin.service:
      name: nginx
      enabled: yes
      state: started

  - name: Deletes directory
    ansible.builtin.file:
       path: /usr/share/nginx/html
       state: absent 

  - name: creats html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: Download the frontend code
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip